configDependencies:
  '@pnpm/plugin-trusted-deps': latest

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@azat-io/*'

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/plugin-trusted-deps/allow.json
allowBuilds:
  esbuild: true
  simple-git-hooks: true

sideEffectsCache: false
