name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443 fulcio.sigstore.dev:443 github.com:443
            registry.npmjs.org:443 rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Install Tools
        uses: ./.github/actions/install-tools

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build Package
        uses: ./.github/actions/build-package

      - name: Create GitHub Release
        run: pnpm run ci:changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clear Package JSON
        run: pnpm run ci:clear

      - name: Publish Root Package to NPM
        run: npm publish --no-git-checks
